# Generated by Django 4.1.3 on 2025-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='test',
            field=models.TextField(default='test'),
        ),
    ]
