# Generated by Django 4.1.3 on 2025-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='test2',
            field=models.TextField(default='test2'),
        ),
    ]
